name: Deploy Talentum with PM2

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.VPS_SSH_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -H ${{ secrets.VPS_HOST }} >> ~/.ssh/known_hosts

      - name: Sync files to VPS
        run: |
          rsync -avz --delete \
            -e "ssh -i ~/.ssh/id_ed25519 -o StrictHostKeyChecking=no" \
            --exclude 'node_modules' \
            --exclude '.git' \
            --exclude 'dist' \
            ./ ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }}:/var/www/html/talentum/

      - name: Build and Restart PM2
        env:
          HOST: ${{ secrets.VPS_HOST }}
          USER: ${{ secrets.VPS_USER }}
        run: |
          ssh -i ~/.ssh/id_ed25519 -o StrictHostKeyChecking=no ${USER}@${HOST} bash -s <<'ENDSSH'
            set -e

            export PATH="/home/yafel/.nvm/versions/node/v22.21.0/bin:$PATH"
            
            cd /var/www/html/talentum

            echo "Installing dependencies..."
            npm ci --silent

            echo "Building project..."
            npm run build

            echo "Restarting PM2..."
            pm2 restart all

            echo "Deployment completed!"
          ENDSSH